### ISSUE TITLE
Add live search to the search engine.

### ISSUE THREAD

**Issue by LukeIsCodingNet** [zorchenhimer/MoviePolls#105]
Add live search to the search engine that filters movies immediately when you start typing similar to Netflix.

**Comment by CptPie** [comment]
Similarly to #103 input checking before submission is only possible with javascript (atleast as far as i am aware) Also the feature you are talking about is called elastic search, which would as far as i am aware require 1 a working database (i.e. not json) and 2 importing and using a fucking massive js library.

**Comment by dbaudisch** [comment]
I have a rudimentary solution for this issue, written in vanilla JS.
Basically filtering by title and hiding the ones not matching.

```js
const voteEntries = Array.from(document.querySelectorAll('.voteRoot'))
document.querySelector('input').addEventListener('keyup', e => {
    voteEntries.forEach(item => item.style.display = item.querySelector('.voteName a').innerText.toLowerCase().includes(e.target.value.toLowerCase()) ? 'block' : 'none')
})
```

@zorchenhimer @CptPie 
I provided a patch file for you:
[moviepolls-issue-105.patch.txt](https://github.com/zorchenhimer/MoviePolls/files/5939754/moviepolls-issue-105.patch.txt)

**Comment by dbaudisch** [comment]
@zorchenhimer @CptPie 
If you guys are fine with my proposal, feel free to commit it

**Comment by CptPie** [comment]
Its fine with me, how about you @zorchenhimer ?

**Comment by CptPie** [comment]
I've prepared a branch which implements the approach from @dbaudisch 
https://github.com/CptPie/MoviePolls/tree/105DynSearch

**Comment by zorchenhimer** [comment]
Yea, I'm ok with that.
