### ISSUE TITLE
Movie history

### ISSUE THREAD

**Issue by CptPie** [zorchenhimer/MoviePolls#12]
We already have all movies saved in the database with the corresponding cycle dates.
It should be feasible to display some sort of history (maybe combined with the search functionality).

**Comment by zorchenhimer** [comment]
A lot of the functionality for this has been added with a7cf06240926704884d75f8dd0968aa3d68c4092, but it could still use some work.  Specifically, it should probably show the most recently ended cycle somewhere on the main page (without clicking through to the history page).
