### ISSUE TITLE
Allow users to vote which movie we watch first.

### ISSUE THREAD

**Issue by LukeIsCodingNet** [zorchenhimer/MoviePolls#123]
Add a new voting feature that allows users to vote on what movie we watch first, when we do watch two movies.

**Comment by CptPie** [comment]
This feature is a) probably not easy to implement (since the watched movies will be choosen by the admin at a non specific time (before/after/during a movienight) so the voting wont be easy to manage time wise) and b) is possibly out of scope.

@zorchenhimer probably has a similar opinion

**Comment by zorchenhimer** [comment]
I agree with @CptPie.  This isn't something that I would use and it would be a pain to implement for little gain.

**Comment by LukeIsCodingNet** [comment]
Ok I agree!
