### ISSUE TITLE
User who added a movie is not displayed (and/or saved)

### ISSUE THREAD

**Issue by CptPie** [zorchenhimer/MoviePolls#18]
When adding a movie there is a field for the user who added the movie.
This field is never updated.

**Comment by CptPie** [comment]
The current Database table for the movie does not support saving the user who added the movie, either we change the table layout or remove this feature (although it would be nice to have in my opinion)

**Comment by zorchenhimer** [comment]
This seems to have been an oversight on my part.  I want the user added data to be saved, but like you pointed out, it's not currently saved yet.
