### ISSUE TITLE
Add a Admin Button to user interface if user has the correct permissions

### ISSUE THREAD

**Issue by CptPie** [zorchenhimer/MoviePolls#27]
With that a admin user doesnt have to move to the admin view via the address bar.

**Comment by zorchenhimer** [comment]
I'm not sure what you mean.  There is a link to the admin pages in the UI: 
![image](https://user-images.githubusercontent.com/6540297/82719940-e62fee00-9c7c-11ea-8320-6a8bfe860514.png)

Granted it isn't positioned correctly, but it's there.

**Comment by CptPie** [comment]
That is strange, on my end the UI looks like this:
![image](https://user-images.githubusercontent.com/23438606/82732977-f5f91200-9d10-11ea-94fe-69857b807469.png)
My user has "priviledges: 1" and is able to change the settings in the config screen.

**Comment by CptPie** [comment]
I just checked the template, apparently the Value that should be assigned in priviledges is "ADMIN", somehow 1 also worked out fine

**Comment by CptPie** [comment]
i close that issue, since the functionality is working fine and the bug is located on the server side.
The new issue will be #28
