### ISSUE TITLE
Limit username length

### ISSUE THREAD

**Issue by zorchenhimer** [zorchenhimer/MoviePolls#33]
Make the limit something reasonable (length of 100?).

Don't allow this:
![image](https://user-images.githubusercontent.com/6540297/84336973-7ff50780-ab66-11ea-840f-170145c1ef78.png)

**Comment by tbal999** [comment]
Hello,

At row 185 in 'user.go' - in func (s *Server) handlerUserNew(w http.ResponseWriter, r *http.Request) {
un := strings.TrimSpace(r.PostFormValue("Username"))

Looks like maybe after this a conditional could be set to check the length and limit it / return it as an invalid username.
