### ISSUE TITLE
Overflow boxes

### ISSUE THREAD

**Issue by CptPie** [zorchenhimer/MoviePolls#38]
We have some "small" issues in some places
![image](https://user-images.githubusercontent.com/23438606/84609735-5fa3b080-aeb8-11ea-8a31-b26276337fcb.png)
![image](https://user-images.githubusercontent.com/23438606/84609771-71855380-aeb8-11ea-92bc-3aef0e3bef90.png)
![image](https://user-images.githubusercontent.com/23438606/84609785-8cf05e80-aeb8-11ea-86bf-1cb3ad7c452e.png)

**Comment by zorchenhimer** [comment]
This should be fixed when #98 is merged.
