### ISSUE TITLE
Voting Limit Restriction doesnt appear to work

### ISSUE THREAD

**Issue by CptPie** [zorchenhimer/MoviePolls#4]
When creating more than 5 movies (i.e. 6) and voting for each one results in one vote for each movie (even though the user only has 5 votes). 
In the account page the available votes are displayed as -1
![image](https://user-images.githubusercontent.com/23438606/81295793-43b71e80-9071-11ea-9b25-ad24374b78c8.png)

**Comment by zorchenhimer** [comment]
I think I accidentally removed the check when I changed the vote code a while back.
