### ISSUE TITLE
Image Display is not working

### ISSUE THREAD

**Issue by CptPie** [zorchenhimer/MoviePolls#42]
When autofilling (both IMDB and MAL) as well as when uploading an image the image is not displayed.
This might have been introduced in fb948615

![image](https://user-images.githubusercontent.com/23438606/84792924-c5955280-aff4-11ea-93bc-4b9992b8f2e9.png)

**Comment by CptPie** [comment]
Relevant debug messages
![image](https://user-images.githubusercontent.com/23438606/84793062-ef4e7980-aff4-11ea-9a27-19ef0cc1f2f4.png)

**Comment by zorchenhimer** [comment]
Yea, looks like I missed that.  I reworked the static file stuff a bit so subfolders would actually work.  I'll have a look.
