### ISSUE TITLE
Text input length limits

### ISSUE THREAD

**Issue by zorchenhimer** [zorchenhimer/MoviePolls#46]
Limit the length of the various text input fields.  Username was already added, but does need to be tweaked to not count zero width spaces (and other weird space characters).

- [ ] Movie Title
- [ ] Movie Description
- [ ] Movie Links

**Comment by zorchenhimer** [comment]
Yea, I'm OK with using that library.

**Comment by CptPie** [comment]
should have been closed with #76 but i forgot the closes keyword in the description ...
