### ISSUE TITLE
Add a github "banner"

### ISSUE THREAD

**Issue by CptPie** [zorchenhimer/MoviePolls#59]
We should add a small banner/button/something else to advertise this repository to an average user.

**Comment by CptPie** [comment]
I did some research and found this repository: https://github.com/tholman/github-corners which has some nice github banners. These banners work without any js and just use vanilla svg transformations.
Since both top corners are occupied by login/menu items i created a corner for the bottom right corner of the screen based on the content of this repostiory, a demo can be found here:
https://www.w3schools.com/code/tryit.asp?filename=GGE5ULAVV75Z
What is your opinion on that @zorchenhimer ?

**Comment by CptPie** [comment]
Updated the demo to display some text on hover https://www.w3schools.com/code/tryit.asp?filename=GGEK05JV45IW

**Comment by zorchenhimer** [comment]
Yea, I'd be OK with putting that in one of the bottom corners.  I'd also be OK with adding a text link to the top menu (or both).
