### ISSUE TITLE
Removing vote when max votes used gives error

### ISSUE THREAD

**Issue by joeyak** [zorchenhimer/MoviePolls#64]
I have used all three votes, and when I click "Remove", I get an error saying I have no votes. I clicked on westworld on the main site, and it sent me to `https://moviepolls.zorchenhimer.com/vote/67` 
![image](https://user-images.githubusercontent.com/27922090/85936014-bbad0280-b8c4-11ea-961b-7aa44aeab5b2.png)
![image](https://user-images.githubusercontent.com/27922090/85936019-c6679780-b8c4-11ea-9856-071f4403d4ba.png)

**Comment by zorchenhimer** [comment]
I thought I had fixed this.  Guess it creeped back in somehow.

**Comment by zorchenhimer** [comment]
Turns out I only fixed this in the front-end code.  The data layer was blocking it this time.
