### ISSUE TITLE
Create db folder on startup if it doesnt exist

### ISSUE THREAD

**Issue by CptPie** [zorchenhimer/MoviePolls#94]
It's getting kinda annoying to create the db folder for the json database by hand.

It should be easy to create the folder in the dataconnector init function.

**Comment by CptPie** [comment]
A bit more information:
The json data backend expects/creates it's file at `db/data.json`.
At the moment the file gets created if it doesn't exist, but creating that file fails, if the folder `db` does not exist already.
A good place to put the folder creation would be before the file creation in the `newJsonConnector` function.

**Comment by zorchenhimer** [comment]
fixed with #96
